### ISSUE TITLE
docker-compose up --build doesn't work

### ISSUE THREAD

**Issue by tadeuqc** [aayani/pet-store#7]
basically all the container are throwing the same error:  

> Error: Cannot find module '/usr/src/app/dist/server.js'

**Comment by aayani** [comment]
The project currently doesn't have a script for building node projects. Have you tried building them individually first?
```
cd owners
yarn
yarn build
```
```
cd owners
yarn
yarn build
```

**Comment by aayani** [comment]
The issue is fixed and resolved with Docker multi-stage build
